FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=1234
ENV N8N_USER_MANAGEMENT_DISABLED=true
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV PORT=5678

EXPOSE 5678

# ใช้ ENTRYPOINT แยกคำสั่งออก เพื่อให้ทำงานบน Render ได้
ENTRYPOINT ["tini", "--"]
CMD ["n8n"]



